services:
  back:
    image: jafber/monoplan-back
    build:
      context: ./back
      dockerfile: Dockerfile
    expose:
      - "5000"
    restart: always
    networks:
      - app_network

  front:
    image: jafber/monoplan-front
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    networks:
      - app_network
    depends_on:
      - back
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  app_network:
    driver: bridge
