# docker build -t jafber/monoplan-back .
# docker run --rm -p 5000:5000 -t jafber/monoplan-back

FROM python:3.12 AS backend
RUN apt-get update
RUN apt-get install -y librsvg2-bin libgl1

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

ENV FLASK_APP=server.py
ENV FLASK_RUN_HOST=0.0.0.0

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "server:app"]
