# docker build -t jafber/monoplan-front .
# docker run --rm -p 5000:80 -t jafber/monoplan-front

# BUILD
FROM node:18 AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install --frozen-lockfile

COPY . .
RUN npm run build

# SERVE
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
