name: Deploy Azure Function App

on:
  push:
    branches:
      - main  # Deploy when pushing to the main branch
  workflow_dispatch:  # Allow manual triggers

jobs:
  deploy:
    name: Deploy to Azure Function App
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Adjust the Python version as needed

      # Step 3: Install Azure Functions Core Tools
      - name: Install Azure Functions Core Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y azure-functions-core-tools-4

      # Step 4: Navigate to the back directory and install dependencies
      - name: Install dependencies
        working-directory: ./back
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 6: Deploy the Function App
      - name: Deploy Function App
        working-directory: ./back
        run: |
          func azure functionapp publish fa-junction24

      # Optional: Cleanup
      - name: Clean up Python cache
        run: |
          find . | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf
