on: push
  branches:
    - main
name: Deploy site to monoplan.jan-berndt.de on push
jobs:
  web-deploy:
    name: Deploy static page
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: Build Project
      working-directory: ./front
      run: |
        npm install
        npm run build
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.samkirkland.com
        username: web111
        password: ${{ secrets.password }}
        local-dir: ./front/dist/
        server-dir: htdocs/monoplan/