name: Deploy frontend + backend

on:
  push:
    branches:
      - main

jobs:
  deploy-front:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Get latest code
        uses: actions/checkout@v4
  
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
        
      - name: Build Project
        working-directory: ./front
        run: |
          npm install
          npm run build

      # https://github.com/marketplace/actions/ftp-deploy
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: cc1.ccnode.org
          username: web111_monoplan
          password: ${{ secrets.JAN_BERNDT_WEBSPACE }}
          local-dir: ./front/dist/
          protocol: ftps
          server-dir: /www/
